name: Deploy Nextjs to EC2 via ssh

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ubuntu/tk-app

            LOG_FILE="$HOME/deploy.log"

            echo "========== $(date) Deploy Started ==========" >> $LOG_FILE

            echo "Pulling latest code..." | tee -a $LOG_FILE
            git reset --hard >> $LOG_FILE 2>&1
            git pull origin main >> $LOG_FILE 2>&1

            echo "Installing dependencies..." | tee -a $LOG_FILE
            npm install >> $LOG_FILE 2>&1

            echo "Building app..." | tee -a $LOG_FILE
            npm run build >> $LOG_FILE 2>&1

            echo "Restarting app with PM2..." | tee -a $LOG_FILE
            pm2 start npm --name tk-app -- start >> $LOG_FILE 2>&1 || pm2 restart tk-app >> $LOG_FILE 2>&1

            echo "Saving PM2 process list..." | tee -a $LOG_FILE
            pm2 save >> $LOG_FILE 2>&1

            echo "Deploy finished at $(date)" | tee -a $LOG_FILE
